export const START_SHOW_UI: String = 'START_SHOW_UI';
export const FINISH_SHOW_UI: String = 'FINISH_SHOW_UI';

export const START_DEPOSIT: String = 'START_DEPOSIT';
export const FINISH_DEPOSIT: String = 'FINISH_DEPOSIT';
export const START_WITHDRAW: String = 'START_WITHDRAW';
export const FINISH_WITHDRAW: String = 'FINISH_WITHDRAW';

export const START_TRANSACTION_MESSAGE: String = 'START_TRANSACTION_MESSAGE';
export const FINISH_TRANSACTION_MESSAGE: String = 'FINISH_TRANSACTION_MESSAGE';
