export const START_SHOW_UI = 'START_SHOW_UI';
export const FINISH_SHOW_UI = 'FINISH_SHOW_UI';

export const START_DEPOSIT = 'START_DEPOSIT';
export const FINISH_DEPOSIT = 'FINISH_DEPOSIT';
export const START_WITHDRAW = 'START_WITHDRAW';
export const FINISH_WITHDRAW = 'FINISH_WITHDRAW';
export const START_TRANSFER = 'START_TRANSFER';
export const FINISH_TRANSFER = 'FINISH_TRANSFER';

export const START_TRANSACTION_MESSAGE = 'START_TRANSACTION_MESSAGE';
export const FINISH_TRANSACTION_MESSAGE = 'FINISH_TRANSACTION_MESSAGE';

export const SET_PARAMETER = 'SET_PARAMETER';
export const CLEAR_PARAMETERS = 'CLEAR_PARAMETERS';

export const SWAP_ACCOUNT = 'SWAP_ACCOUNT';
